// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Rafeeq.Models;

[Table("Availability")]
public partial class Availability
{
    [Key]
    public int AvailabilityId { get; set; }

    public int? UserId { get; set; }

    public int? DayOfWeek { get; set; }

    public TimeSpan? StartTime { get; set; }

    public TimeSpan? EndTime { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Availabilities")]
    public virtual User User { get; set; }
}