// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Rafeeq.Models;

public partial class ChatMessage
{
    [Key]
    public int MessageId { get; set; }

    public int? BookingId { get; set; }

    public int? ConversationId { get; set; }

    public int? SenderId { get; set; }

    public string MessageText { get; set; }

    public bool? IsRead { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? SentAt { get; set; }

    [ForeignKey("BookingId")]
    [InverseProperty("ChatMessages")]
    public virtual Booking Booking { get; set; }

    [ForeignKey("ConversationId")]
    [InverseProperty("Messages")]
    public virtual ChatConversation Conversation { get; set; }

    [InverseProperty("Message")]
    public virtual ICollection<ChatAttachment> ChatAttachments { get; set; } = new List<ChatAttachment>();

    [InverseProperty("Message")]
    public virtual ICollection<MessageReadStatus> ReadStatuses { get; set; } = new List<MessageReadStatus>();

    [ForeignKey("SenderId")]
    [InverseProperty("ChatMessages")]
    public virtual User Sender { get; set; }
}
