// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Rafeeq.Models;

public partial class ChatAttachment
{
    [Key]
    public int AttachmentId { get; set; }

    public int? MessageId { get; set; }
    public bool IsVoiceMessage { get; set; } = false;


    [Required]
    [StringLength(255)]
    public string FilePath { get; set; }

    [Required]
    [StringLength(100)]
    public string FileName { get; set; }

    public int FileSize { get; set; }

    [Required]
    [StringLength(100)]
    public string ContentType { get; set; }

    [ForeignKey("MessageId")]
    [InverseProperty("ChatAttachments")]
    public virtual ChatMessage Message { get; set; }
}