// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Rafeeq.Models;

public partial class MentorSkill
{
    [Key]
    public int MentorSkillId { get; set; }

    public int? UserId { get; set; }

    public int? SkillId { get; set; }

    [ForeignKey("SkillId")]
    [InverseProperty("MentorSkills")]
    public virtual Skill Skill { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("MentorSkills")]
    public virtual User User { get; set; }
}