// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Rafeeq.Models;

public partial class MenteeSkill
{
    [Key]
    public int MenteeSkillId { get; set; }

    public int? UserId { get; set; }

    public int? SkillId { get; set; }

    [ForeignKey("SkillId")]
    [InverseProperty("MenteeSkills")]
    public virtual Skill Skill { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("MenteeSkills")]
    public virtual User User { get; set; }
}