// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Rafeeq.Models;

public partial class Notification
{
    [Key]
    public int NotificationId { get; set; }

    public int? UserId { get; set; }

    [StringLength(255)]
    public string Message { get; set; }

    public bool? IsRead { get; set; }

    [StringLength(50)]
    public string Type { get; set; }

    public int? RelatedEntityId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Notifications")]
    public virtual User User { get; set; }
}