// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Rafeeq.Models;

public partial class Review
{
    [Key]
    public int ReviewId { get; set; }

    public int? ReviewerId { get; set; }

    public int? ReviewedUserId { get; set; }

    public int? BookingId { get; set; }

    public int? Rating { get; set; }

    public string Comment { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    [ForeignKey("BookingId")]
    [InverseProperty("Reviews")]
    public virtual Booking Booking { get; set; }

    [ForeignKey("ReviewedUserId")]
    [InverseProperty("ReviewReviewedUsers")]
    public virtual User ReviewedUser { get; set; }

    [ForeignKey("ReviewerId")]
    [InverseProperty("ReviewReviewers")]
    public virtual User Reviewer { get; set; }
}