// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Rafeeq.Models;

public partial class Skill
{
    [Key]
    public int SkillId { get; set; }

    [Required]
    [StringLength(100)]
    public string Name { get; set; }
    public bool IsDeleted { get; set; } = false;

    [InverseProperty("Skill")]
    public virtual ICollection<MenteeSkill> MenteeSkills { get; set; } = new List<MenteeSkill>();

    [InverseProperty("Skill")]
    public virtual ICollection<MentorSkill> MentorSkills { get; set; } = new List<MentorSkill>();
}