// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Rafeeq.Models;

[Index("Email", Name = "UQ__Users__A9D105348DC3A58E", IsUnique = true)]
public partial class User
{
    [Key]
    public int UserId { get; set; }

    [Required]
    [StringLength(100)]
    public string FullName { get; set; }

    [Required]
    [StringLength(100)]
    public string Email { get; set; }

    [Required]
    [StringLength(255)]
    public string PasswordHash { get; set; }

    [StringLength(255)]
    public string ?ProfilePicture { get; set; }

    public string? Bio { get; set; }

    public bool? IsEmailVerified { get; set; }

    public int? RoleId { get; set; }

    public bool? IsActive { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [StringLength(100)]
    public string? ExternalId { get; set; }

    [StringLength(50)]
    public string? ExternalType { get; set; }

    public string? ExternalToken { get; set; }

    public bool? IsMentor { get; set; }

    public bool? IsInterviewer { get; set; }

    public bool? IsDeleted { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? HourlyRate { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<Availability> Availabilities { get; set; } = new List<Availability>();

    [InverseProperty("Mentee")]
    public virtual ICollection<Booking> BookingMentees { get; set; } = new List<Booking>();

    [InverseProperty("Mentor")]
    public virtual ICollection<Booking> BookingMentors { get; set; } = new List<Booking>();

    [InverseProperty("Sender")]
    public virtual ICollection<ChatMessage> ChatMessages { get; set; } = new List<ChatMessage>();

    [InverseProperty("User")]
    public virtual ICollection<MenteeSkill> MenteeSkills { get; set; } = new List<MenteeSkill>();

    [InverseProperty("User")]
    public virtual ICollection<MentorSkill> MentorSkills { get; set; } = new List<MentorSkill>();

    [InverseProperty("User")]
    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    [InverseProperty("ReviewedUser")]
    public virtual ICollection<Review> ReviewReviewedUsers { get; set; } = new List<Review>();

    [InverseProperty("Reviewer")]
    public virtual ICollection<Review> ReviewReviewers { get; set; } = new List<Review>();

    [ForeignKey("RoleId")]
    [InverseProperty("Users")]
    public virtual Role Role { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<UserToken> UserTokens { get; set; } = new List<UserToken>();
    
    public ICollection<MenteeCV> CVs { get; set; }
    public ICollection<CVComment> CVComments { get; set; }

}